<form id="xmlForm" class="form-horizontal" action="<?php echo $this->actionUrl; ?>" method="POST" ENCTYPE="multipart/form-data">
    <div class="control-group">
        <label class="control-label" for="inputDebug">Debug</label>
        <div class="controls" style="padding-top: 3px;">
            <input id="inputDebug" name="debug" type="checkbox" checked="checked" value="1">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputXML">XML</label>
        <div class="controls">
            <textarea id="inputXML" name="inputXML" style="width: 550px;height: 300px;"><?php if (isset($this->xmlString)) echo $this->xmlString; ?></textarea>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputXMLFile">XML Upload</label>
        <div class="controls">
            <input id="inputXMLFile" name="inputXMLFile" type="file">
        </div>
    </div>
    <input type="hidden" name="sent" value="1">
    <div class="control-group">
        <div class="controls">
            <input type="button" class="btn" value="abschicken" onclick="
                if(!document.getElementById('inputDebug').checked){
                    if(confirm('Den Updatevorgang starten ?')){
                        document.getElementById('xmlForm').submit();
                    }else{
                        return false;
                    }
                }else{
                    document.getElementById('xmlForm').submit();
                }
                   ">
        </div>
    </div>
</form>

<?php if($this->sent): ?>
<style>
    #xmlResults .identical{
        font-weight: bold;
        color: darkgreen;
    }
    #xmlResults .error{
        font-weight: bold;
        color: darkred;
    }
</style>
<div id="xmlResults">
    <p style="text-align: center;">
        <?php if($this->debug): ?>
            <span class="identical">Update m&ouml;glich</span> / <span class="error">Update nicht m&ouml;glich ( md5 Werte nicht identisch / Datei existiert nicht )</span>
        <?php else: ?>
            <span class="identical">Update erfolgreich</span> / <span class="error">Update verweigert ( md5 Werte nicht identisch / Datei existiert nicht )</span>
        <?php endif; ?>
    </p>
    <table id="xmlResultTable" class="table table-bordered">
        <thead>
            <tr>
                <th>Datei</th>
                <th>Md5 Xml-Content</th>
                <th>Md5 Datei</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->xmlResults as $result): ?>
                <?php
                    if($result["md5"] == $result["fileMd5"]){
                        $class = "identical";
                    }else{
                        $class = "error";
                    }
                ?>
                <tr>
                    <td><?php echo $result["filePath"]; ?></td>
                    <td class="<?php echo $class; ?>"><?php echo $result["md5"]; ?></td>
                    <td class="<?php echo $class; ?>"><?php if($result["fileMd5"]){ echo $result["fileMd5"];}else{ echo "angegebene Datei existiert nicht !";}; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>