<form class="form-horizontal" action="<?php echo $this->actionUrl; ?>" method="POST">
    <div class="control-group">
        <label class="control-label" for="inputText">Text</label>
        <div class="controls">
            <textarea id="inputText" name="inputText" style="width: 550px;height: 300px;"><?php if (isset($this->array["inputText"]["formInput"])) echo $this->array["inputText"]["formInput"]; ?></textarea>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputPath">Datei Pfad</label>
        <div class="controls">
            <select name="configPath">
                <option value="">Bitte ausw&auml;hlen</option>
                <?php foreach ($this->paths as $key => $value): ?>
                    <option value="<?php echo $value; ?>" <?php if (isset($this->array["configPath"]["formInput"]) && $this->array["configPath"]["formInput"] == $value): ?>selected="selected"<?php endif; ?>><?php echo $key; ?></option>
                <?php endforeach; ?>
            </select>
            <span style="font-weight: bold;">/</span> 
            <input style="width: 313px;" type="text" id="inputPath" name="path" placeholder="Dateipfad" value="<?php if (isset($this->array["path"]["formInput"])) echo $this->array["path"]["formInput"]; ?>">
        </div>
    </div>
    <input type="hidden" name="sent" value="1">
    <div class="control-group">
        <div class="controls">
            <input type="submit" class="btn" value="abschicken" onclick="
                document.getElementById('greyOverlay').style.display = 'block';
                var opts = {
                    lines: 13, // The number of lines to draw
                    length: 16, // The length of each line
                    width: 14, // The line thickness
                    radius: 25, // The radius of the inner circle
                    corners: 1, // Corner roundness (0..1)
                    rotate: 0, // The rotation offset
                    color: '#ddd', // #rgb or #rrggbb
                    speed: 1, // Rounds per second
                    trail: 44, // Afterglow percentage
                    shadow: true, // Whether to render a shadow
                    hwaccel: false, // Whether to use hardware acceleration
                    className: 'spinner', // The CSS class to assign to the spinner
                    zIndex: 2e9, // The z-index (defaults to 2000000000)
                    top: '350', // Top position relative to parent in px
                    left: 'auto' // Left position relative to parent in px
                };
                var target = document.getElementById('greyOverlay');
                var spinner = new Spinner(opts).spin(target);
                   ">
        </div>
    </div>
</form>

<?php if ($this->array["sent"]): ?>

    <?php
    $errorPath = false;
    $identical = false;
    if (isset($this->array["inputText"]["md5"])) {
        $inputText = $this->array["inputText"]["md5"];
    }

    if (isset($this->array["path"]["md5"])) {
        if ($this->array["path"]["md5"]) {
            $path = $this->array["path"]["md5"];
        }
        else {
            $path = "angegebene Datei existiert nicht !";
            $errorPath = true;
        }
    }
    else {
        $path = "&nbsp;";
    }

    if ($path == $inputText) {
        $identical = true;
    }
    ?>
    <table class="table">
        <thead>
        <th style="width: 150px;">Type</th>
        <th>Md5</th>
        </thead>
        <tbody>
            <tr>
                <td>Texteingabe</td>
                <td <?php if ($identical) : ?>style="color:darkgreen;font-weight: bold;"<?php endif; ?>><?php echo $inputText; ?></td>
            </tr>
            <tr>
                <td>Datei</td>
                <td <?php if ($identical) : ?>style="color:darkgreen;font-weight: bold;"<?php endif; ?><?php if ($errorPath) : ?>style="color:darkred;font-weight: bold;"<?php endif; ?>><?php echo $path; ?></td>
            </tr>
        </tbody>
    </table>
<?php endif; ?>