<div class="lwBoxLeftnavi" onClick="changeUrl('admin.php?obj=admin');">zur&uuml;ck</div>

<div class="lwBoxLeftContent" style="font-size: 12px;">
    <div class="cNavEntry" onclick="changeUrl('?obj=updater&module=md5checker');">
        <span style="color: #fff;font-size: 12px;">md5Checker</span>
    </div>
    <div class="cNavEntry" onclick="changeUrl('?obj=updater&module=systemupdater');">
        <span style="color: #fff;font-size: 12px;">System Updater ( Files + DB )</span>
    </div>
    
</div>